/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef scheduler_CONSTANTS_H
#define scheduler_CONSTANTS_H

#include "scheduler_types.h"



class schedulerConstants {
 public:
  schedulerConstants();

};

extern const schedulerConstants g_scheduler_constants;



#endif
