/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "scheduler_types.h"



const char* TaskInfo::ascii_fingerprint = "2581CC094302C11CA20AE04D9D1437C6";
const uint8_t TaskInfo::binary_fingerprint[16] = {0x25,0x81,0xCC,0x09,0x43,0x02,0xC1,0x1C,0xA2,0x0A,0xE0,0x4D,0x9D,0x14,0x37,0xC6};

uint32_t TaskInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_framework_name = false;
  bool isset_cmd = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->framework_name);
          isset_framework_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->cmd);
          isset_cmd = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->arguments);
          this->__isset.arguments = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->candidate_ips);
          this->__isset.candidate_ips = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->cpu);
          this->__isset.cpu = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->memory);
          this->__isset.memory = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_framework_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_cmd)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TaskInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("TaskInfo");
  xfer += oprot->writeFieldBegin("framework_name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->framework_name);
  xfer += oprot->writeFieldEnd();
  xfer += oprot->writeFieldBegin("cmd", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->cmd);
  xfer += oprot->writeFieldEnd();
  if (this->__isset.arguments) {
    xfer += oprot->writeFieldBegin("arguments", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeString(this->arguments);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.candidate_ips) {
    xfer += oprot->writeFieldBegin("candidate_ips", ::apache::thrift::protocol::T_STRING, 4);
    xfer += oprot->writeString(this->candidate_ips);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.cpu) {
    xfer += oprot->writeFieldBegin("cpu", ::apache::thrift::protocol::T_DOUBLE, 5);
    xfer += oprot->writeDouble(this->cpu);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.memory) {
    xfer += oprot->writeFieldBegin("memory", ::apache::thrift::protocol::T_DOUBLE, 6);
    xfer += oprot->writeDouble(this->memory);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}


