/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef cellet_CONSTANTS_H
#define cellet_CONSTANTS_H

#include "cellet_types.h"



class celletConstants {
 public:
  celletConstants();

};

extern const celletConstants g_cellet_constants;



#endif
