/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "cellet_constants.h"



const celletConstants g_cellet_constants;

celletConstants::celletConstants() {
}



