/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef scheduler_TYPES_H
#define scheduler_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>





typedef struct _TaskInfo__isset {
  _TaskInfo__isset() : arguments(false), candidate_ips(false), need_cpu(false), need_memory(false) {}
  bool arguments;
  bool candidate_ips;
  bool need_cpu;
  bool need_memory;
} _TaskInfo__isset;

class TaskInfo {
 public:

  static const char* ascii_fingerprint; // = "CB4EC85350124CB04BE63BAC46B8B12F";
  static const uint8_t binary_fingerprint[16]; // = {0xCB,0x4E,0xC8,0x53,0x50,0x12,0x4C,0xB0,0x4B,0xE6,0x3B,0xAC,0x46,0xB8,0xB1,0x2F};

  TaskInfo() : framework_name(""), id(0), cmd(""), arguments(""), candidate_ips(""), need_cpu(0), need_memory(0) {
  }

  virtual ~TaskInfo() throw() {}

  std::string framework_name;
  int64_t id;
  std::string cmd;
  std::string arguments;
  std::string candidate_ips;
  double need_cpu;
  int32_t need_memory;

  _TaskInfo__isset __isset;

  bool operator == (const TaskInfo & rhs) const
  {
    if (!(framework_name == rhs.framework_name))
      return false;
    if (!(id == rhs.id))
      return false;
    if (!(cmd == rhs.cmd))
      return false;
    if (__isset.arguments != rhs.__isset.arguments)
      return false;
    else if (__isset.arguments && !(arguments == rhs.arguments))
      return false;
    if (__isset.candidate_ips != rhs.__isset.candidate_ips)
      return false;
    else if (__isset.candidate_ips && !(candidate_ips == rhs.candidate_ips))
      return false;
    if (__isset.need_cpu != rhs.__isset.need_cpu)
      return false;
    else if (__isset.need_cpu && !(need_cpu == rhs.need_cpu))
      return false;
    if (__isset.need_memory != rhs.__isset.need_memory)
      return false;
    else if (__isset.need_memory && !(need_memory == rhs.need_memory))
      return false;
    return true;
  }
  bool operator != (const TaskInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TaskInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};



#endif
