/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "scheduler_constants.h"



const schedulerConstants g_scheduler_constants;

schedulerConstants::schedulerConstants() {
}



