/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "collector_constants.h"



const collectorConstants g_collector_constants;

collectorConstants::collectorConstants() {
}



