// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Collector.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class CollectorHandler : virtual public CollectorIf {
 public:
  CollectorHandler() {
    // Your initialization goes here
  }

  void Match(std::string& _return, const std::string& str_ad) {
    // Your implementation goes here
    printf("Match\n");
  }

  void Heartbeat(const MachineInfo& info) {
    // Your implementation goes here
    printf("Heartbeat\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CollectorHandler> handler(new CollectorHandler());
  shared_ptr<TProcessor> processor(new CollectorProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

