/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef collector_CONSTANTS_H
#define collector_CONSTANTS_H

#include "collector_types.h"



class collectorConstants {
 public:
  collectorConstants();

};

extern const collectorConstants g_collector_constants;



#endif
